name: Build
on:
  - pull_request

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: pnpm/action-setup@v1.2.0
        with:
          version: 4.11.1
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - run: pnpm run lint:js
      - run: pnpm run lint:hbs
      - run: pnpm test
